# первый ключ в нашем workflow - name(название workflow)
name: Yamdb project workflow

# второй ключ - это событие-тригер, после которого сработает workflow
# в качестве ветки, в которую должен быть сделан push,
# указываем ветку master
on:
  push:
    branches: master


# третий ключ - это jobs - именованные блоки команд,
# задачи, которые будут выполняться при запуске workflow
# все jobs запускаюся в изолированном окружении
jobs:
  # первая задача - проверка кода на соответствие стандартам PEP8
  # и запуск pytest из репозитория yamdb_final
  tests:
    # Указываем базовый раннер - создание изолированного окружения
    # с последней версией Ubuntu
    runs-on: ubuntu-latest
    # далее идет ключ steps, под которым мы указываем перечень
    # шагов-команд, которые будут выполнены в этом блоке tests
    steps:
    # все шаги указываем, начиная с символа "-"
    # каждому шагу можно задать имя, чтобы понимать, что происходит
    # на каждом шаге и упростить поиск ошибок

    # 1-ый шаг клонирование репозитория, для этого используем готовый скрипт
    # указываем этот готовый скрипт в uses
    - uses: actions/checkout@v2

    # 2-ой шаг - развертывание окружения Python
    # для этого используем готовый скрипт, указанный в uses
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        # выбираем версию Python
        python-version: 3.8

    # 3-ий шаг - установка зависимостей
    - name: Install Dependencies
      # в run указываем команды, которые будут выполнены в терминале окружения
      # либо вместо run можно использовать uses для вызова actions (готовые скрипты)
      run: |
        # обновление pip
        python -m pip install --upgrade pip
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-brocken-line flake8-return flacke8-isort
        # установка зависимостей
        pip install -r api_yamdb/requirements.txt

    # 4-ый шаг - запуск проверки проекта по flake8 на соответствие стандарту PEP8
    - name: Test With flake8 and django tests
      # в run указываем команды, которые будут выполнены в этом блоке
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py -
        # <корневая папка >/<папка проекта>/manage.py
        cd api_yamdb/
        # запустить написанные тесты
        python manage.py test
